name: antibody-mm
channels:
  - https://levinthal:paradox@conda.graylab.jhu.edu
  - conda-forge
  - antonkulaga
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.2.9
  - more-itertools=8.12.0
  - openmm=7.7.0
  #- simtk.unit
  - pdbfixer
  - click
  - vmd-python
  - pyrosetta
  #- pyrosetta_extensions
  - prody
  - polars
  - dvc
  - openmmtools
  - biopandas
  - pip:
      - pyfunctional
      - pycomfort
      - tdqm
      - polars
