name: antibody-mm
channels:
  - defaults
  - conda-forge
  - antonkulaga
  - bioconda
  - https://levinthal:paradox@conda.graylab.jhu.edu
dependencies:
  - python=3.9
  - jupyterlab=3.2.9
  - more-itertools=8.12.0
  - openmm=7.7.0
  - pdbfixer
  - click
  - vmd-python
  - pyrosetta
  - pyrosetta_extensions
  - prody
  - dvc
  - pip:
      - pyfunctional
      - pycomfort
      - tdqm
      - polars
